[package]
name = "re-tex"
version = "0.1.0"
edition = "2024"

[dependencies]
better_default = "1.0"
byteorder = "1.5"
gdeflate = "0.4"
strum = { version = "0.27", features = ["derive"] }
thiserror = "2.0"

[dev-dependencies]
regex = "1.11"
